spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dashboard
    username: root
    password: Algorithms94
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true